### ISSUE TITLE
How you handling the audio?

### ISSUE THREAD

**Issue by jfrux** [opentok/archiving-composer#5]
Not seeing that logic

**Comment by jfrux** [comment]
Doesn't appear to mix the audio from both videos... so ffmpeg only knows to take audio from the first stream.

**Comment by jcague** [comment]
Thanks @joshuairl, now it's just a simple script to start playing with. Any developer could modify it to decide whether to mix all audios, or switch between them.

**Comment by jfrux** [comment]
No, Thank you for all you do for the community.
Are there zero plans to make this work exactly like the composed videos that the OpenTok system already does?  For people who may want individual streams AND composed streams available.

I'm having trouble getting your script to combine the streams accurately and both streams at right framerate + both audio mixed correctly.

Any tips on getting those things smoothed out?

**Comment by jfrux** [comment]
I'm new to ffmpeg and all of this in general.
Just as an FYI... 
It seems like if I convert the initial webm's to mp4 first, then do the time sync logic and create the "chunk" files they come out more accurate and are easier to work with... but maybe I'm just getting confused.

Once they are in mp4 container it does seem to be much snappier and easier to sync them up.

Just a random tidbit that I've discovered as I'm trying to get it working good for my purposes.
