### ISSUE TITLE
Installation instructions for ubuntu?

### ISSUE THREAD

**Issue by dylanjha** [opentok/archiving-composer#8]
How to install the required dependencies for ffmpeg on ubuntu?

**Comment by FranciscoCano** [comment]
Not sure what you mean. You just:

 sudo apt-get install ffmpeg

and all the dependencies will be installed as well...

**Comment by dylanjha** [comment]
ubuntu 14.04 doesn't have it http://askubuntu.com/questions/432542/is-ffmpeg-missing-from-the-official-repositories-in-14-04

I found another way to compile it from the binary
